name: Push
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: format('{0}-{1}', ${{ github.workflow }}-${{ github.ref }}, ${{ github.head_ref || github.run_id }})
  cancel-in-progress: false

jobs:
  concurrency-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sleep 60
