name: Push
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  concurrency-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sleep 60

# a
# b
# c
# 
# 
# 
# 
# 
# 
